{{
    apiVersionParam = "api-version=7.1"
    apiVersionPreviewParam = "api-version=7.1-preview.3"
}}


# Get current iteration
# @name currentIteration
GET {{baseUrl}}/work/teamsettings/iterations?$timeframe=current&{{apiVersionParam}}
Authorization: Basic {{token}}
{{
  iterationId = response.parsedBody.value[0].id
}}
###
GET {{baseUrl}}/work/teamsettings/iterations/{{iterationId}}?{{apiVersionParam}}
Authorization: Basic {{token}}
###
# @disabled
# User Story is an item with rel == null
GET {{baseUrl}}/work/teamsettings/iterations/{{iterationId}}/workitems?{{apiVersionPreviewParam}}
Authorization: Basic {{token}}
###
GET {{baseUrl}}/wit/workItems/1?$expand=Relations
Authorization: Basic {{token}}
###
GET {{baseUrl}}/wit/workitems?ids=1&{{apiVersionParam}}&fields=System.Title,System.AreaPath,System.TeamProject,System.IterationPath
Authorization: Basic {{token}}
###
GET {{baseUrl}}/wit/workitems?ids=1&{{apiVersionParam}}&$expand=Relations,Links
Authorization: Basic {{token}}
###
GET {{baseUrl}}/wit/workitems?ids=2&{{apiVersionParam}}
Authorization: Basic {{token}}
###
GET {{baseUrl}}/wit/classificationNodes/Areas?$depth=10&{{apiVersionParam}}
Authorization: Basic {{token}}
###
GET {{baseUrl}}/wit/tags?{{apiVersionParam}}
Authorization: Basic {{token}}
###
# @name GetTeam
GET {{orgUrl}}/teams?{{apiVersionPreviewParam}}
Authorization: Basic {{token}}

{{
    teamId = response.parsedBody.value[0].id
    projectId = response.parsedBody.value[0].projectId
}}
###
GET {{orgUrl}}/projects/{{projectId}}/teams/{{teamId}}/members?{{apiVersionParam}}
Authorization: Basic {{token}}
###
GET {{orgUrl}}/projects/Scrum?{{apiVersionParam}}
Authorization: Basic {{token}}
###
GET {{orgUrl}}/projects/Scrum/teams/Scrum%20Team/members
Authorization: Basic {{token}}
###

GET {{baseUrl}}/wit/workitemrelationtypes?{{apiVersionParam}}
Authorization: Basic {{token}}
###
GET {{baseUrl}}/wit/workitemtypes/Task/fields/Microsoft.VSTS.Common.Activity?$expand=All&{{apiVersionParam}}
Authorization: Basic {{token}}
###
# Microsoft.VSTS.Scheduling.RemainingWork
# Microsoft.VSTS.Scheduling.OriginalEstimate

POST {{baseUrl}}/wit/workitems/$Task?{{apiVersionParam}}
Authorization: Basic {{token}}
Content-Type: application/json-patch+json

[
	{
		"op": "add",
		"path": "/fields/System.Title",
		"value": "New sample task"
  	},
	{
		"op": "add",
		"path": "/fields/System.AreaPath",
		"value": "IDEAapp_2018"
  	},
	{
		"op": "add",
		"path": "/fields/System.TeamProject",
		"value": "IDEAapp_2018"
  	},
	{
		"op": "add",
		"path": "/fields/System.IterationPath",
		"value": "IDEAapp_2018\\Iteration 1"
  	},
	{
		"op": "add",
		"path": "/fields/Microsoft.VSTS.Common.Activity",
		"value": "Development"
  	},
	{
		"op": "add",
		"path": "/fields/Microsoft.VSTS.Scheduling.RemainingWork",
		"value": 7
  	},
	{
		"op": "add",
		"path": "/fields/Microsoft.VSTS.Scheduling.OriginalEstimate",
		"value": 7
  	},
	{
		"op": "add",
		"path": "/relations/-",
		"value": {
			"rel": "System.LinkTypes.Hierarchy-Reverse",
			"url": "https://dev.azure.com/ipatalas0593/_apis/wit/workItems/13"
		}
	}
]

# Add work item: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/create?view=azure-devops-rest-5.0
# Add link https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.0#add_a_link
###
# https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.0
PATCH {{baseUrl}}/wit/workitems/66?{{apiVersionParam}}
Authorization: Basic {{token}}
Content-Type: application/json-patch+json

[
	{
		"op": "add",
		"path": "/fields/System.Title",
		"value": "small task - edited"
  	},
	{
		"op": "add",
		"path": "/fields/Microsoft.VSTS.Common.Activity",
		"value": "Development"
  	},
	{
		"op": "add",
		"path": "/fields/Microsoft.VSTS.Scheduling.RemainingWork",
		"value": 2
  	},
	{
		"op": "add",
		"path": "/fields/Microsoft.VSTS.Scheduling.OriginalEstimate",
		"value": 2
  	},
	{
		"op": "add",
		"path": "/fields/System.AssignedTo",
		"value": "Ireneusz Patalas<fido@list.pl>"
  	},
    {
        "op": "add",
        "path": "/fields/System.Tags",
        "value": "Tag1; Tag2"
    }
]
###

POST {{baseUrl}}/wit/workitems/$User%20Story?{{apiVersionParam}}
Authorization: Basic {{token}}
Content-Type: application/json-patch+json

[
	{
		"op": "add",
		"path": "/fields/System.Title",
		"value": "test 2"
  	},
	{
		"op": "add",
		"path": "/fields/System.IterationPath",
		"value": "MyFirstProject\\Iteration 1"
  	}
]